// Copyright 2026 The FlutterTV Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/// Builds `PORTING_REPORT.md` from the aggregated [PortingResult]s the
/// scaffolder collected while transforming a plugin's native sources.
///
/// The report is the human-facing half of the porter's "honest about
/// limits" promise: every method that was stubbed because it touches a
/// tvOS-incompatible API is listed with the reason and a suggested action,
/// every flagged-for-review API is called out, and every stripped iOS-only
/// import is recorded with its source location so a reviewer can audit the
/// port without re-reading the diff.
library;

import 'compatibility_database.dart';
import 'porting_result.dart';
import 'source_analyzer.dart';

/// Stateless renderer. Pure function of its inputs so it golden-tests
/// cleanly; inject [today] in tests to keep output deterministic.
class ReportEmitter {
  const ReportEmitter();

  /// Renders the full `PORTING_REPORT.md` body for [source] given the
  /// per-file [results] produced by [SwiftPorter]. Pass [today] (a
  /// `YYYY-MM-DD` string) to override the generation date in tests.
  String render({
    required PluginSource source,
    required List<PortingResult> results,
    String? today,
  }) {
    final List<PortingFinding> all = <PortingFinding>[
      for (final PortingResult r in results) ...r.findings,
    ];

    final List<PortingFinding> importStrips = all
        .where((PortingFinding f) => f.action == FindingAction.importStripped)
        .toList();
    final List<PortingFinding> stubFindings = all
        .where((PortingFinding f) => f.action == FindingAction.stubbedMethod)
        .toList();
    final List<PortingFinding> partialFindings = all
        .where((PortingFinding f) => f.action == FindingAction.flagged)
        .toList();
    final List<PortingFinding> todoFindings = all
        .where((PortingFinding f) => f.action == FindingAction.taggedWithTodo)
        .toList();

    final Set<String> detectedMethods = <String>{
      for (final PortingResult r in results) ...r.detectedMethods,
    };
    final Set<String> stubbedMethods = <String>{
      for (final PortingResult r in results) ...r.stubbedCases,
    };
    final Set<String> partialMethods = <String>{
      for (final PortingFinding f in partialFindings)
        if (f.enclosingMethod != null) f.enclosingMethod!,
    };
    final List<String> portedMethods = (detectedMethods
            .difference(stubbedMethods)
            .difference(partialMethods)
            .toList())
      ..sort();

    final int manualReviewCount = partialFindings.length + todoFindings.length;

    // `taggedWithTodo` = an `unsupported` API used at type / top-level
    // scope (e.g. `class X: SFSafariViewControllerDelegate`,
    // `let v = WKWebView()` in a property). The porter can stub a
    // method-channel *handler body*, but it cannot remove a type the
    // class declaration depends on — so the generated package will NOT
    // compile on tvOS until a human rewrites those sites. Detect it and
    // say so loudly instead of letting Xcode be the messenger.
    final Set<String> blockingApis = <String>{
      for (final PortingFinding f in todoFindings) f.pattern.name,
    };
    final bool willNotCompile = blockingApis.isNotEmpty;

    final StringBuffer b = StringBuffer()
      ..writeln('# ${source.outputPackageName} — porting report')
      ..writeln()
      ..writeln(
          'Generated by `flutter-tvos plugin port` on ${today ?? _today()}.')
      ..writeln()
      ..writeln(
          'Source: `${source.packageName}` ${source.sourceVersion ?? '(no version)'} '
          '(path: `${source.directory.path}`)')
      ..writeln('Base platform: ${source.sourcePlatform} '
          '(${_languageLabel(source)})')
      ..writeln('Output: `./${source.outputPackageName}`')
      ..writeln();

    if (willNotCompile) {
      b
        ..writeln('> ## ⚠️ This plugin is not buildable on tvOS as-is')
        ..writeln('>')
        ..writeln('> It uses ${_oxford(blockingApis.toList()..sort())} at '
            'type / top-level scope — APIs that **do not exist on tvOS**. '
            'The porter stubs method-channel handlers, but it cannot '
            'invent these types, so the generated package WILL NOT '
            'compile until you rewrite those sites by hand (or decide '
            'this plugin has no meaningful tvOS implementation). See '
            '“Manual review items” below; each is marked '
            '`// TODO(porter)` in the source.')
        ..writeln();
    } else {
      b
        ..writeln('> ✅ No tvOS-incompatible APIs detected at type level — '
            'the generated package is expected to compile on tvOS '
            '(still review stubbed/partial items below).')
        ..writeln();
    }

    b
      ..writeln('## Summary')
      ..writeln()
      ..writeln('| Status | Count |')
      ..writeln('|---|---|')
      ..writeln('| Methods ported as-is | ${portedMethods.length} |')
      ..writeln('| Methods stubbed (iOS-only) | ${stubbedMethods.length} |')
      ..writeln('| tvOS build outlook | '
          '${willNotCompile ? '❌ will NOT compile (manual work required)' : '✅ expected to compile'} |')
      ..writeln('| Manual review items | $manualReviewCount |')
      ..writeln();

    b
      ..writeln('## Methods')
      ..writeln();
    if (detectedMethods.isEmpty) {
      b
        ..writeln('No `case "<method>":` handlers were detected in the source. '
            'Either the plugin dispatches method calls in a non-standard way '
            '(review `tvos/Classes/` by hand) or it has no method channel.')
        ..writeln();
    } else {
      for (final String m in portedMethods) {
        b
          ..writeln('### `$m` ✓ ported')
          ..writeln()
          ..writeln('No tvOS-incompatible APIs detected in this handler. '
              'Copied across unchanged.')
          ..writeln();
      }
      for (final String m in (partialMethods.toList()..sort())) {
        b.writeln('### `$m` ⚠️ partial');
        b.writeln();
        for (final PortingFinding f in partialFindings
            .where((PortingFinding f) => f.enclosingMethod == m)) {
          b
            ..writeln(
                'Source: `${f.fileRelativePath}:${f.line}` (`${f.matchedText}`)')
            ..writeln('Note: ${_collapse(f.pattern.note)}')
            ..writeln();
        }
      }
      for (final String m in (stubbedMethods.toList()..sort())) {
        b.writeln('### `$m` ✗ stubbed');
        b.writeln();
        for (final PortingFinding f in stubFindings
            .where((PortingFinding f) => f.enclosingMethod == m)) {
          b
            ..writeln(
                'Source: `${f.fileRelativePath}:${f.line}` (`${f.matchedText}`)')
            ..writeln('Reason: ${f.pattern.name} — ${_collapse(f.pattern.note)}')
            ..writeln('Suggested action: leave the stub (callers receive '
                '`MissingPluginException` on tvOS, which cleanly surfaces the '
                'limitation) or implement a tvOS-native equivalent if one '
                'exists.')
            ..writeln();
        }
      }
    }

    b
      ..writeln('## Imports removed')
      ..writeln();
    if (importStrips.isEmpty) {
      b
        ..writeln('None. Every `import` in the source compiles on tvOS.')
        ..writeln();
    } else {
      for (final PortingFinding f in importStrips) {
        b.writeln('- `${f.matchedText}` (`${f.fileRelativePath}:${f.line}`)');
      }
      b.writeln();
    }

    b
      ..writeln('## Manual review items')
      ..writeln();
    if (manualReviewCount == 0) {
      b
        ..writeln('None flagged automatically. You should still skim '
            '`tvos/Classes/` — regex-based porting is best-effort and cannot '
            'catch every obfuscated API use.')
        ..writeln();
    } else {
      var n = 1;
      for (final PortingFinding f in partialFindings) {
        b.writeln('${n++}. `${f.fileRelativePath}:${f.line}` — '
            '${f.pattern.name} (${_severityWord(f.pattern.severity)}). '
            '${_collapse(f.pattern.note)}');
      }
      for (final PortingFinding f in todoFindings) {
        b.writeln('${n++}. `${f.fileRelativePath}:${f.line}` — '
            '${f.pattern.name} is used outside a recognised method handler '
            'and was tagged with `// TODO(porter)` rather than auto-stubbed. '
            'Decide how tvOS should behave here by hand.');
      }
      b.writeln();
    }

    b
      ..writeln('## Checklist')
      ..writeln()
      ..writeln('- [ ] Read every `✗ stubbed` method above and confirm '
          'returning `FlutterMethodNotImplemented` is acceptable on tvOS.')
      ..writeln('- [ ] Review every `⚠️ partial` method against a real Apple '
          'TV (behaviour differs from iOS).')
      ..writeln('- [ ] Confirm the removed imports were not load-bearing for '
          'still-supported code paths.')
      ..writeln('- [ ] `flutter-tvos build tvos --simulator --debug` from the '
          "plugin's example app compiles the generated registrant.")
      ..writeln('- [ ] Bump the version and update `CHANGELOG.md` before '
          'publishing.')
      ..writeln()
      ..writeln('---')
      ..writeln()
      ..writeln('Manual review required. Read this report top-to-bottom '
          'before publishing `${source.outputPackageName}`.');

    return b.toString();
  }

  /// Compatibility-DB notes are wrapped multi-line strings. The report is
  /// Markdown where soft-wrapped prose reads better as one line.
  String _collapse(String note) =>
      note.replaceAll('\n', ' ').replaceAll(RegExp(r' {2,}'), ' ').trim();

  /// `[A]`→`A`, `[A,B]`→`A and B`, `[A,B,C]`→`A, B and C`.
  String _oxford(List<String> items) {
    if (items.length == 1) {
      return items.first;
    }
    return '${items.sublist(0, items.length - 1).join(', ')} and ${items.last}';
  }

  String _severityWord(Severity s) => switch (s) {
        Severity.unsupported => 'unsupported',
        Severity.partial => 'partial',
        Severity.info => 'info',
      };

  String _languageLabel(PluginSource source) => switch (source.sourceLanguage) {
        SourceLanguage.swift => 'Swift',
        SourceLanguage.objc => 'Objective-C',
        SourceLanguage.mixed => 'Swift + Objective-C',
        SourceLanguage.unknown => 'unknown',
      };

  static String _today() {
    final DateTime now = DateTime.now();
    final String yyyy = now.year.toString().padLeft(4, '0');
    final String mm = now.month.toString().padLeft(2, '0');
    final String dd = now.day.toString().padLeft(2, '0');
    return '$yyyy-$mm-$dd';
  }
}
