// Copyright 2026 The FlutterTV Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Templates start with `$header` (an already-rendered comment block) rather
// than a literal newline. The `leading_newlines_in_multiline_strings` lint
// would force us to insert a blank line between the file header and the
// first line of code in the rendered output, which we don't want.
// ignore_for_file: leading_newlines_in_multiline_strings

/// Inline templates for the `flutter-tvos plugin port` scaffolder.
///
/// These are intentionally Dart strings rather than separate `.tmpl` files so
/// the porter has zero runtime dependencies on the package's own asset layout.
/// Each function returns a complete file body. Mustache-style `{{...}}` is not
/// used — interpolation is plain Dart `${...}` so the templates are lintable
/// and refactorable.
library;

import 'source_analyzer.dart';

/// Default copyright holder line baked into generated source files when the
/// caller doesn't override it via `--license-holder`.
const String kDefaultLicenseHolder = 'The FlutterTV Authors';

/// Renders the BSD-3-style header that goes at the top of every generated
/// source file (Dart, Swift, Objective-C, podspec, README).
String renderLicenseHeader({
  required String holder,
  required String commentPrefix,
  String? sourcePlugin,
}) {
  final String today = _today();
  final lines = <String>[
    'Copyright 2026 $holder. All rights reserved.',
    'Use of this source code is governed by a BSD-style license that can be',
    'found in the LICENSE file.',
    '',
    'Generated on $today by `flutter-tvos plugin port`.',
    if (sourcePlugin != null) 'Source plugin: $sourcePlugin',
  ];
  return lines.map((String l) => l.isEmpty ? commentPrefix.trim() : '$commentPrefix$l').join('\n');
}

/// Renders the output package's `pubspec.yaml`.
String renderPubspec({required PluginSource source, required String licenseHolder}) {
  final String description = _quoteForYaml(
    'tvOS implementation of ${source.basePackageName}.',
  );
  final homepage = 'https://github.com/fluttertv/${source.outputPackageName}';
  final String? platformInterface = source.platformInterfacePackage;
  final String? dartPluginClass = source.dartPluginClass;
  final buf = StringBuffer()
    ..writeln('name: ${source.outputPackageName}')
    ..writeln('description: $description')
    ..writeln('version: 0.0.1')
    ..writeln('homepage: $homepage')
    ..writeln('# Generated by `flutter-tvos plugin port`. See PORTING_REPORT.md.')
    ..writeln('# License holder: $licenseHolder')
    ..writeln()
    ..writeln('environment:')
    ..writeln('  sdk: ">=3.0.0 <4.0.0"')
    ..writeln('  flutter: ">=3.13.0"')
    ..writeln()
    ..writeln('dependencies:')
    ..writeln('  flutter:')
    ..writeln('    sdk: flutter');
  if (platformInterface != null) {
    // Carry the source's own constraint so `pub get` resolves; only fall
    // back to `any` when the source didn't pin one. Range constraints
    // (`>=1.0.0 <2.0.0`) and anything with YAML-significant characters
    // must be quoted — `key: >=1.0.0` is otherwise a YAML block scalar.
    final String raw = source.platformInterfaceConstraint ?? 'any';
    final bool needsQuote = RegExp(r'[>< ]').hasMatch(raw);
    final String constraint =
        needsQuote ? '"${raw.replaceAll('"', r'\"')}"' : raw;
    buf.writeln('  $platformInterface: $constraint');
  }
  buf
    ..writeln()
    ..writeln('dev_dependencies:')
    ..writeln('  flutter_lints: ^4.0.0')
    ..writeln('  flutter_test:')
    ..writeln('    sdk: flutter')
    ..writeln()
    ..writeln('flutter:')
    ..writeln('  plugin:')
    ..writeln('    platforms:')
    ..writeln('      tvos:')
    ..writeln('        pluginClass: ${source.pluginClass}');
  if (dartPluginClass != null) {
    buf.writeln('        dartPluginClass: $dartPluginClass');
  }
  return buf.toString();
}

/// Renders the output package's CocoaPods podspec.
///
/// Per the project rules in flutter-tvos/CLAUDE.md, the podspec must NOT use
/// `s.dependency 'Flutter'` (the Flutter pod doesn't declare tvOS support).
/// Flutter.framework is picked up via FRAMEWORK_SEARCH_PATHS instead.
String renderPodspec({required PluginSource source, required String licenseHolder}) {
  // A modular SwiftPM package keeps its public headers under an
  // `include/<module>/` directory and `#import`s them via that prefix.
  // Collapse it into a single CocoaPods module the way the upstream
  // package's own podspec does: compile every source, and expose ONLY
  // the `include/` headers (the SwiftPM public surface) so the module
  // umbrella stays internally consistent and the `include/…` import
  // paths keep resolving after CocoaPods flattens the framework
  // headers. Applies to multi-target packages AND single-target ones
  // that use the `include/` convention (e.g. sqflite_darwin). The plain
  // legacy `Classes/` layout keeps the flat globs.
  final bool modular = source.isMultiTargetSpm || source.spmModularHeaders;
  final String sourceFilesGlob =
      modular ? "'Classes/**/*.{h,m,mm,swift}'" : "'Classes/**/*'";
  final String publicHeadersGlob =
      modular ? "'Classes/**/include/**/*.h'" : "'Classes/**/*.h'";
  return '''
#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html.
# Run `pod lib lint ${source.outputPackageName}.podspec` to validate before publishing.
#
# Generated by `flutter-tvos plugin port`. License holder: $licenseHolder.
#
Pod::Spec.new do |s|
  s.name             = '${source.outputPackageName}'
  s.version          = '0.0.1'
  s.summary          = 'tvOS implementation of ${source.basePackageName}.'
  s.description      = <<-DESC
tvOS implementation of ${source.basePackageName}, the federated platform
package that ships native code targeting Apple tvOS.
                       DESC
  s.homepage         = 'https://github.com/fluttertv/${source.outputPackageName}'
  s.license          = { :file => '../LICENSE' }
  s.author           = { '$licenseHolder' => 'noreply@fluttertv.dev' }
  s.source           = { :path => '.' }
  s.source_files     = $sourceFilesGlob
  s.public_header_files = $publicHeadersGlob
  s.platform         = :tvos, '13.0'
  s.swift_version    = '5.0'

  # IMPORTANT: this podspec must not depend on the Flutter CocoaPod. That
  # pod does not declare tvOS support, so adding a dependency on it breaks
  # `pod install` for tvOS consumers. Flutter.framework is resolved via
  # FRAMEWORK_SEARCH_PATHS, populated by the host app's Podfile.
  s.xcconfig         = {
    'FRAMEWORK_SEARCH_PATHS' => '"\${PODS_ROOT}/../Flutter"',
    'OTHER_SWIFT_FLAGS'      => '\$(inherited) -DTARGET_OS_TV',
  }
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
end
''';
}

/// Renders a Swift stub at `tvos/Classes/<PluginClass>.swift`.
///
/// Phase 1 deliberately writes a minimal stub: the user is expected to paste
/// their iOS implementation in. The header explains that, and the
/// `register(with:)` body is a placeholder that wires the channel name from
/// the source plugin (so `pod install` and the registrant compile).
String renderSwiftStub({required PluginSource source, required String licenseHolder}) {
  final String header = renderLicenseHeader(
    holder: licenseHolder,
    commentPrefix: '// ',
    sourcePlugin: source.packageName,
  );
  final channelHint = '${source.basePackageName}_tvos';
  return '''$header
//
// TODO(porter): paste the iOS implementation of `${source.pluginClass}` here.
// The class signature, register(with:), and method handlers should mostly
// transfer verbatim from your iOS Swift source. Strip imports and call sites
// for tvOS-incompatible APIs (WebKit, UIPasteboard, LocalAuthentication, etc.)
// and stub the corresponding handler cases with `result(FlutterMethodNotImplemented)`.

import Flutter
import UIKit

public class ${source.pluginClass}: NSObject, FlutterPlugin {
  public static func register(with registrar: FlutterPluginRegistrar) {
    let channel = FlutterMethodChannel(
      name: "$channelHint",
      binaryMessenger: registrar.messenger())
    let instance = ${source.pluginClass}()
    registrar.addMethodCallDelegate(instance, channel: channel)
  }

  public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
    // TODO(porter): replace with the iOS handler body.
    result(FlutterMethodNotImplemented)
  }
}
''';
}

/// Renders a 1-line Objective-C bridging header that lets the Swift class be
/// imported from the GeneratedPluginRegistrant.m without an `@import` cycle.
String renderBridgingHeader({required PluginSource source, required String licenseHolder}) {
  final String header = renderLicenseHeader(
    holder: licenseHolder,
    commentPrefix: '// ',
    sourcePlugin: source.packageName,
  );
  return '''$header
//
// Used by Xcode to bridge Swift sources to the Objective-C registrant.
// Add Objective-C imports here when you call out to UIKit / GameController etc.

#import <UIKit/UIKit.h>
''';
}

/// Renders the Dart entry point at `lib/<plugin>_tvos.dart`.
///
/// Phase 1 emits a `registerWith()` that's a no-op — when the user pastes
/// their iOS Dart implementation in (or wires it via the platform interface
/// in phase 3), they replace the body. The class modifier is `base` so it
/// works as a subclass of a `base class` platform interface (the Dart 3
/// requirement documented in flutter-tvos/CLAUDE.md).
String renderDartEntry({required PluginSource source, required String licenseHolder}) {
  final String header = renderLicenseHeader(
    holder: licenseHolder,
    commentPrefix: '// ',
    sourcePlugin: source.packageName,
  );
  final String? interface = source.platformInterfacePackage;
  final String classBody;
  if (interface != null && source.dartPluginClass != null) {
    final String dartClass = source.dartPluginClass!;
    classBody =
        '''
import 'package:$interface/$interface.dart';

/// tvOS implementation of `${source.basePackageName}`.
///
/// Registered by Flutter's federated plugin runner via `registerWith()`. The
/// `base` modifier is required because the platform interface declares
/// itself as `base class`.
base class $dartClass extends ${_platformInterfaceClassName(interface)} {
  /// Registers this implementation as the default `${source.basePackageName}`
  /// platform implementation on tvOS.
  static void registerWith() {
    ${_platformInterfaceClassName(interface)}.instance = $dartClass();
  }

  // TODO(porter): override the platform interface methods that the iOS
  // implementation overrides. Methods you do not override fall through to
  // the platform interface's default implementations, which usually throw
  // `UnimplementedError` — that is the right behaviour for tvOS-incompatible
  // calls.
}
''';
  } else {
    classBody =
        '''
/// tvOS implementation of `${source.basePackageName}`.
///
/// This plugin does not declare a federated platform interface. The
/// `registerWith()` hook is intentionally empty — native registration
/// happens via `tvos/Classes/${source.pluginClass}.swift`.
class ${source.basePackageName.replaceAllMapped(RegExp(r'(_)(.)'), (m) => m[2]!.toUpperCase()).replaceFirstMapped(RegExp(r'^.'), (m) => m[0]!.toUpperCase())}Tvos {
  /// Registers this implementation as the default `${source.basePackageName}`
  /// platform implementation on tvOS. No-op for non-federated plugins.
  static void registerWith() {}
}
''';
  }
  return '$header\n//\n// Dart entry point for the tvOS implementation.\n\n$classBody';
}

/// Renders a placeholder test that loads the Dart entry point, exercising
/// `registerWith()`. Keeps `dart test` green out of the box.
String renderTestStub({required PluginSource source, required String licenseHolder}) {
  final String header = renderLicenseHeader(
    holder: licenseHolder,
    commentPrefix: '// ',
    sourcePlugin: source.packageName,
  );
  final String? dartClass = source.dartPluginClass;
  if (dartClass != null) {
    // Reference the registrant class so the package import is actually
    // used (no `unused_import`) and the smoke test verifies the package
    // compiles and the class is reachable.
    return '''$header

import 'package:flutter_test/flutter_test.dart';
import 'package:${source.outputPackageName}/${source.outputPackageName}.dart';

void main() {
  test('package compiles and exposes $dartClass', () {
    expect($dartClass, isNotNull);
  });
}
''';
  }
  // No federated Dart class to reference — keep a dependency-free smoke
  // test rather than an unused package import.
  return '''$header

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('test harness runs', () {
    expect(1 + 1, 2);
  });
}
''';
}

/// Renders the README that ships with the generated package.
String renderReadme({required PluginSource source, required String licenseHolder}) {
  return '''# ${source.outputPackageName}

The tvOS implementation of [`${source.basePackageName}`](https://pub.dev/packages/${source.basePackageName}).

> Generated by [`flutter-tvos plugin port`](https://github.com/fluttertv/flutter-tvos)
> from `${source.packageName}`. Read `PORTING_REPORT.md` before publishing.

## Usage

This is a federated plugin implementation. Apps that already depend on
`${source.basePackageName}` and target tvOS only need to add this package as a
dependency:

```yaml
dependencies:
  ${source.basePackageName}: ^<latest>
  ${source.outputPackageName}: ^0.0.1
```

The plugin registers automatically via Flutter's federated registry — no
explicit imports required from app code.

## Status

| Platform | Implemented |
|----------|-------------|
| Apple TV (`appletvos`) | yes |
| Apple TV simulator (`appletvsimulator`) | yes |

## License

$licenseHolder under a BSD-3-Clause license. See `LICENSE` for the full text.
''';
}

/// Renders a CHANGELOG seed.
String renderChangelog({required PluginSource source}) {
  return '''## 0.0.1

* Initial tvOS scaffolding generated by `flutter-tvos plugin port` from
  `${source.packageName}`.
''';
}

/// Renders a tight, focused `analysis_options.yaml`.
String renderAnalysisOptions() {
  return '''
include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
''';
}

/// Renders a `.gitignore` covering the standard Dart/Flutter outputs plus the
/// CocoaPods-derived files that show up under `tvos/`.
String renderGitignore() {
  return '''
# Dart / Flutter
.dart_tool/
build/
.flutter-plugins
.flutter-plugins-dependencies
.packages
.pub/

# CocoaPods
tvos/Pods/
tvos/Podfile.lock
tvos/.symlinks/
tvos/Flutter/Flutter.framework
tvos/Flutter/Flutter.podspec

# IDE
.idea/
.vscode/
*.iml

# macOS
.DS_Store
''';
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

String _today() {
  final now = DateTime.now();
  final String yyyy = now.year.toString().padLeft(4, '0');
  final String mm = now.month.toString().padLeft(2, '0');
  final String dd = now.day.toString().padLeft(2, '0');
  return '$yyyy-$mm-$dd';
}

String _quoteForYaml(String s) {
  // Use double quotes; escape backslashes and double-quotes.
  final String escaped = s.replaceAll(r'\', r'\\').replaceAll('"', r'\"');
  return '"$escaped"';
}

/// `url_launcher_platform_interface` → `UrlLauncherPlatform`.
///
/// Best-effort heuristic: drops the `_platform_interface` suffix, then
/// upper-CamelCases the rest, then appends `Platform`. Matches what most
/// Flutter teams pick. The user can adjust the rendered import if their
/// interface uses a different name.
String _platformInterfaceClassName(String interfacePackage) {
  var base = interfacePackage;
  if (base.endsWith('_platform_interface')) {
    base = base.substring(0, base.length - '_platform_interface'.length);
  }
  final String camel = base
      .split('_')
      .where((String p) => p.isNotEmpty)
      .map((String p) => p[0].toUpperCase() + p.substring(1))
      .join();
  return '${camel}Platform';
}
