// Copyright 2026 The FlutterTV Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter_tools/src/base/file_system.dart';
import 'package:meta/meta.dart';

// Rendered manifests intentionally start with `// swift-tools-version:` (which
// must be the first line of a Package.swift), not a blank line.
// ignore_for_file: leading_newlines_in_multiline_strings

/// Generates the Swift Package Manager packages a tvOS app build needs to
/// consume federated `*_tvos` plugins (Flutter 3.44+ default), mirroring how
/// stock Flutter wires SPM for iOS/macOS — but reimplemented here because the
/// upstream orchestration (`FlutterDarwinPlatform`) only knows iOS/macOS and we
/// don't patch the SDK.
///
/// Two generated packages, written under `tvos/Flutter/ephemeral/Packages/`:
///
/// 1. **`FlutterFramework`** — wraps the tvOS `Flutter.xcframework` as a SwiftPM
///    `.binaryTarget`. Once this is in the resolved package graph, the `Flutter`
///    module becomes importable by every plugin target in the build — which is
///    why federated plugins declare no Flutter dependency of their own (verified
///    against stock plugins like `network_info_plus`, whose manifests are
///    `dependencies: []` yet `import Flutter`).
///
/// 2. **`FlutterGeneratedPluginSwiftPackage`** — the umbrella. Its single target
///    depends on `FlutterFramework` plus each discovered plugin's product, so
///    linking the umbrella into Runner pulls in every plugin (and Flutter). The
///    product is `static` so the plugins' symbols land in the Runner binary.
///
/// This is a pure generator: it only writes manifests and symlinks. Wiring the
/// umbrella into the Xcode project (and removing the now-redundant manual
/// Flutter.framework embed) is the project-integration step.
class TvosSwiftPackageManager {
  TvosSwiftPackageManager({required FileSystem fileSystem}) : _fs = fileSystem;

  final FileSystem _fs;

  /// Name of the umbrella package/target, matching stock Flutter so the Xcode
  /// integration objects line up.
  static const String kGeneratedPluginsPackageName = 'FlutterGeneratedPluginSwiftPackage';

  /// Name of the package/target that vends `Flutter.xcframework`.
  static const String kFlutterFrameworkPackageName = 'FlutterFramework';

  /// tvOS deployment floor the generated packages declare. Must be ≤ the app's
  /// `TVOS_DEPLOYMENT_TARGET` or SwiftPM rejects the dependency graph.
  static const String kDefaultDeploymentTarget = '13.0';

  /// Writes the `FlutterFramework` package into [packageDirectory] and symlinks
  /// [xcframework] inside it (binary targets must reference a local path).
  ///
  /// Re-runnable: the manifest is rewritten and the symlink refreshed each call.
  void generateFlutterFrameworkPackage({
    required Directory packageDirectory,
    required Directory xcframework,
  }) {
    packageDirectory.createSync(recursive: true);
    packageDirectory
        .childFile('Package.swift')
        .writeAsStringSync(renderFlutterFrameworkManifest());

    final Link link = packageDirectory.childLink(xcframework.basename);
    if (link.existsSync()) {
      link.deleteSync();
    }
    link.createSync(xcframework.absolute.path);
  }

  /// Writes the `FlutterGeneratedPluginSwiftPackage` umbrella into
  /// [packageDirectory], symlinking each plugin under `.packages/<name>` and
  /// depending on [flutterFrameworkRelativePath] (the path to the
  /// `FlutterFramework` package, relative to [packageDirectory]).
  ///
  /// Returns the rendered umbrella manifest (also written to disk).
  String generatePluginsSwiftPackage({
    required Directory packageDirectory,
    required List<TvosSpmPlugin> plugins,
    required String flutterFrameworkRelativePath,
    String deploymentTarget = kDefaultDeploymentTarget,
  }) {
    packageDirectory.createSync(recursive: true);

    // SwiftPM requires a target to have a sources directory. The umbrella has
    // no code of its own — a single empty file satisfies the toolchain.
    final Directory sources = packageDirectory
        .childDirectory('Sources')
        .childDirectory(kGeneratedPluginsPackageName);
    sources.createSync(recursive: true);
    sources.childFile('$kGeneratedPluginsPackageName.swift').writeAsStringSync(
      '// Generated by flutter-tvos. This package brings together the tvOS\n'
      '// implementations of every federated plugin the app depends on.\n',
    );

    // Symlink each plugin package under `.packages/<name>` so the manifest can
    // reference a stable relative path regardless of where the plugin lives.
    final Directory packagesDir = packageDirectory.childDirectory('.packages');
    packagesDir.createSync(recursive: true);
    final pluginRefs = <_PluginRef>[];
    for (final TvosSpmPlugin plugin in plugins) {
      final Link link = packagesDir.childLink(plugin.name);
      if (link.existsSync()) {
        link.deleteSync();
      }
      link.createSync(_fs.directory(plugin.packagePath).absolute.path);
      pluginRefs.add(
        _PluginRef(
          name: plugin.name,
          relativePath: '.packages/${plugin.name}',
          productName: plugin.libraryName,
        ),
      );
    }

    final String manifest = renderPluginsUmbrellaManifest(
      plugins: pluginRefs,
      flutterFrameworkRelativePath: flutterFrameworkRelativePath,
      deploymentTarget: deploymentTarget,
    );
    packageDirectory.childFile('Package.swift').writeAsStringSync(manifest);
    return manifest;
  }

  /// Renders the `FlutterFramework` package manifest. Static content: it just
  /// vends the symlinked `Flutter.xcframework` as a binary target.
  @visibleForTesting
  static String renderFlutterFrameworkManifest() {
    return '''// swift-tools-version: 5.9
// Generated by flutter-tvos. Do not edit.
//
// Vends the tvOS Flutter engine (Flutter.xcframework) to the Swift package
// graph so federated plugin targets can `import Flutter` without declaring a
// dependency of their own.
import PackageDescription

let package = Package(
  name: "$kFlutterFrameworkPackageName",
  products: [
    .library(name: "$kFlutterFrameworkPackageName", targets: ["$kFlutterFrameworkPackageName"]),
  ],
  targets: [
    .binaryTarget(name: "$kFlutterFrameworkPackageName", path: "Flutter.xcframework"),
  ]
)
''';
  }

  /// Renders the umbrella `FlutterGeneratedPluginSwiftPackage` manifest.
  ///
  /// SwiftPM derives a dynamic library's `CFBundleIdentifier` from the product
  /// name and rejects underscores, so plugin *product* names are hyphenated
  /// (e.g. `shared_preferences_tvos` → `shared-preferences-tvos`), matching the
  /// library name federated plugins declare. The package name (used for the
  /// path dependency) keeps the underscores.
  @visibleForTesting
  static String renderPluginsUmbrellaManifest({
    required List<_PluginRef> plugins,
    required String flutterFrameworkRelativePath,
    String deploymentTarget = kDefaultDeploymentTarget,
  }) {
    final dependencies = <String>[
      '    .package(name: "$kFlutterFrameworkPackageName", path: "$flutterFrameworkRelativePath"),',
      for (final _PluginRef p in plugins)
        '    .package(name: "${p.name}", path: "${p.relativePath}"),',
    ];
    final targetDependencies = <String>[
      '        .product(name: "$kFlutterFrameworkPackageName", package: "$kFlutterFrameworkPackageName"),',
      for (final _PluginRef p in plugins)
        '        .product(name: "${p.productName}", package: "${p.name}"),',
    ];
    return '''// swift-tools-version: 5.9
// Generated by flutter-tvos. Do not edit.
import PackageDescription

let package = Package(
  name: "$kGeneratedPluginsPackageName",
  platforms: [
    .tvOS("$deploymentTarget"),
  ],
  products: [
    .library(name: "$kGeneratedPluginsPackageName", type: .static, targets: ["$kGeneratedPluginsPackageName"]),
  ],
  dependencies: [
${dependencies.join('\n')}
  ],
  targets: [
    .target(
      name: "$kGeneratedPluginsPackageName",
      dependencies: [
${targetDependencies.join('\n')}
      ]
    ),
  ]
)
''';
  }
}

/// A federated tvOS plugin to include in the umbrella package: its [name]
/// (matching the SwiftPM package name in its `tvos/Package.swift`), the
/// [libraryName] (the `.library(name:)` product the umbrella links), and the
/// path to the directory containing that `Package.swift`.
@immutable
class TvosSpmPlugin {
  TvosSpmPlugin({required this.name, required this.packagePath, String? libraryName})
      : libraryName = libraryName ?? name.replaceAll('_', '-');

  final String name;
  final String packagePath;

  /// The SwiftPM product name the umbrella references. Defaults to the
  /// hyphenated package name (the porter convention), but a hand-authored
  /// plugin may declare any product name, so callers that read the manifest
  /// pass the parsed `.library(name:)` here rather than assuming the form.
  final String libraryName;
}

/// Internal: a resolved plugin reference for manifest rendering.
@immutable
class _PluginRef {
  const _PluginRef({
    required this.name,
    required this.relativePath,
    required this.productName,
  });

  final String name;
  final String relativePath;

  /// SwiftPM product (library) name the umbrella links against.
  final String productName;
}
